exports.run = async (client, msg, args) => {
   const random = require("random-animal")
         random.cat().then(url => {
    msg.channel.send({embed: {
            color: 0xd45555,
            title: `:cat: Meow...`,
            image: {
                url: url
            },
            footer: {
                text: `Generated by random.cat`
            }
        }
    });
    console.log(`Treating ${msg.content} by ${msg.author.tag} from ${msg.guild} as a command.`);
    });
}
  config: {}
