const random = require("random-animal");

module.exports = (msg, client) => {
    random.dog().then(url => {
     msg.channel.send({embed: {
             color: 0xd45555,
             title: `:dog: Woof...`,
             image: {
                 url: url
             },
             footer: {
                text: `Generated by random.dog`
            }
         }
     });
     console.log(`Treating ${msg.content} by ${msg.author.tag} from ${msg.guild} as a command.`);
 });
 }
 config: {}